name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.Deploy }}
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: blog/.vuepress/dist/
        COMMIT_MESSAGE: Auto deploy from Github Actions
